### ISSUE TITLE
function loadRegion(regionfile)

### ISSUE THREAD

**Issue by carajillu** [michellab/jedi-utilities#1]
This function contains only:

```
return 0
```

so the script crashes when trying to read the grid limits from _region.dim_ instead of a ligand files. I wrote this:

```
def loadRegion(regionfile):
     region={'min':[],'max':[]}
     filein=open(regionfile,'r')
     for line in filein:
         if line.startswith('#') or len(line.split())!=3:
            continue
         line=line.split()
         region['min'].append(float(line[1]))
         region['max'].append(float(line[2]))
     filein.close()
     return region
```

and uncommented the lines in function _defineGrid_ that say:

```
mincoords = region['min']
maxcoords = region['max']
```

and now it seems to work fine (let's hope I have not created 10K bugs by doing this)

**Comment by jmichel80** [comment]
Excellent ! I recall now of course the script is unfinished in various places. You will have to make code changes to make it work more generally. 

Can you make sure you are on the devel branch of jedi-utilities ? 
If so commit your code changes to the repository now. 

Quick github cheatsheet

git clone https://github.com/michellab/sire #this will do an initital 'checkout' of sire
git checkout devel #switch to devel branch
git pull origin devel #update from the online repository
#now do all your changes in the files you need
git status #(optiona)
git add \* #(sometimes adding individual files is better for commit messages rather than using *)
git commit -m 'your message' # we should think of a standard nomenclature here
git push origin devel #push updates to the repository

This git cheat sheet is also quite useful:
https://training.github.com/kit/downloads/github-git-cheat-sheet.pdf

Other useful commands:
git status #gives you info about not commited files
git branch #tells you on which branch you are currently working (which should never, be master!)

Ask Stefano/Toni advice if you are stuck.
